services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaija-gallery:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
